declare module '*.jpg';
declare module '*.jpeg';
declare module '*.png';
declare module '*.gif';
declare module '*.svg';
declare module '*.JPG';
declare module '*.JPEG';
declare module '*.PNG'; 
declare module 'pdf-to-text';
